const mongoose = require("mongoose");

const UserSchema = new mongoose.Schema({
    userName:{
        type:String,
        require:true,
        min:3,
        max:20,
        unique:true
    },
    fullName:{
        type:String,
        require:true,
        min:3,
        max:20,
    },
    email:{
        type:String,
        require:true,
        max:50,
        unique:true,
    },
    verified:{
        type:Boolean,
        default:false
    },
    password:{
        type:String,
        require:true,
        min:6,
    },
    refreshToken:{
        type:String,
        default:""
    },
    profilePicture:{
        public_id:{
            type:String,
        },
        url:{
            type:String,
        },
    },
    coverPicture:{
        type:String,
        default:""
    },
    followers:{
        type:Array,
        default:[]
    },
    following:{
        type:Array,
        default:[]
    },
    isAdmin:{
        type:Boolean,
        default:false
    },
    desc:{
        type:String,
        max:50
    },
    city:{
        type:String,
        max:50
    },
    from:{
        type:String,
        max:50
    },
    location:{
        type:String,
        max:20
    },
    realtionship:{
        type:Number,
        enum:[1,2,3]
    },
    socialLink1:{
        type:String,
    },
    socialLink2:{
        type:String,
    }
},{timestamps:true});

module.exports=mongoose.model("User",UserSchema);